// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations/seed/studio run against the session-mode pooler (or direct
    // connection) via DIRECT_URL, while runtime traffic uses the transaction
    // pooler (DATABASE_URL, port 6543). Transaction pooling breaks DDL/migrations.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
